# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ksm < Formula
  desc ""
  homepage "https://github.com/ck0ne9000/kubernetes-secrets-manager"
  version "0.2.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ck0ne9000/kubernetes-secrets-manager/releases/download/0.2.4/kubernetes-secrets-manager_0.2.4_darwin_amd64.tar.gz"
      sha256 "d08f98596a3301ba7b2341eacfd66585ead752e1051729285d46a7c2eac49605"

      def install
        bin.install "ksm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ck0ne9000/kubernetes-secrets-manager/releases/download/0.2.4/kubernetes-secrets-manager_0.2.4_darwin_arm64.tar.gz"
      sha256 "28c741cd005d0c15282a4668152a423844b4d8f3ac63a9c06d7144d484b4dc63"

      def install
        bin.install "ksm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ck0ne9000/kubernetes-secrets-manager/releases/download/0.2.4/kubernetes-secrets-manager_0.2.4_linux_amd64.tar.gz"
      sha256 "1e00fbd3c68dc630c0577dd886999703d6716e24d52b2b9bb515f9ce5bf90705"
      def install
        bin.install "ksm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ck0ne9000/kubernetes-secrets-manager/releases/download/0.2.4/kubernetes-secrets-manager_0.2.4_linux_arm64.tar.gz"
      sha256 "deea9803f4203733371dfe3d208e67447307b4e5a60f52a44f5d0ba7bbb52f9c"
      def install
        bin.install "ksm"
      end
    end
  end
end
